version: '3.8'

services:
  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    environment:
      # LLM Configurations
      - LLM_PROVIDER=gemini
      - GROQ_API_KEY= <place ur api key here>
      - GOOGLE_API_KEY=<place ur api key here>
      
      # SMTP System Assistant Account Configurations
      - SMTP_SERVER=smtp.gmail.com
      - SMTP_PORT=587
      - SMTP_USERNAME=<place ur assitant email  here>
      - SMTP_PASSWORD=<place ur smtp password here >

  frontend:
    build:
      context: ./frontend
    ports:
      - "5173:5173"
    command: npm run dev -- --host
    depends_on:
      - backend